<?php

namespace App\DataFixtures;

use App\Entity\Song;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $song1 = new Song();
        $song1->setTitle('Avril Lavigne - Bite Me');
        $song1->setFullTextInThisColumn("Hey you, you should've known better, better to fuck with someone like me.Hey you, forever and ever you're gonna wish I was your wifey.Don't act so innocent.This was no accident.You planned this in the end.And now it's over.Say what you want to say.You lied and I got played.You threw it all away.And now it's over.Just face it.We didn't make it.You bit off more than you can chew.Can you taste it?.Hey you, you should've known better, better to fuck with someone like me.Hey you, forever and ever you're gonna wish I was your wifey.Should've held on, should've treated me right.I gave you one chance, you don't get it twice.Hey you, and we'll be together never, so baby you can bite me.Don't hold your breath.'Cause you're still choking on your words.Those things you said.Might be the last ones that I heard.So come pick up your clothes from the front yard.Sprinklers on, burn the rest in the backyard.Should've had the guts just to say goodbye.Now you're gonna have regrets for the rest of your life.Just face it.We didn't make it.You bit off more than you can chew.Can you taste it?.Hey you, you should've known better, better to fuck with someone like me.Hey you, forever and ever you're gonna wish I was your wifey.Should've held on, should've treated me right.I gave you one chance, you don't get it twice.Hey you, and we'll be together never, so baby you can bite me.I bet you taste me on the tip of your tongue.Tip of your tongue, tip of your tongue.I fell fast when I know I shoulda run.Know I shoulda run, know I shoulda run.I bet you taste me on the tip of your tongue.Tip of your tongue, tip of your tongue.I fell fast when I know I shoulda run.Know I shoulda run, know I shoulda run.Hey you, you should've known better, better to fuck with someone like me (Like me).Hey you, forever and ever you're gonna wish I was your wifey.Should've held on, should've treated me right (Yeah yeah yeah).I gave you one chance, you don't get it twice (Yeah yeah yeah).Hey you, and we'll be together never, so baby you can bite me");
        $song1->setCreatedAt(new \DateTimeImmutable());
        $song1->setUpdatedAt(new \DateTimeImmutable());
        $manager->persist($song1);
        $manager->flush();

        $song1 = new Song();
        $song1->setTitle('NCT 127 - Favorite (Vampire)');
        $song1->setFullTextInThisColumn("Oh yeah yeah.Ah yeah ah yeah.Ah darlin' darlin'.You're my Favorite girl.Oh yeah.Yeolbyeonggati dagawa.Nal myeolmang shigyeo.Ain't afraid at all.Nae segye sansani buseojyeo.Neoreul tamhage dwego.Buljangnanira hae (Quit that).Gashireul gajyeonne (Hands down).Papyeoni dwae beorin Crown (Take that).Geu sungyeolhan dok.Nan kkaemureotgo deurimashyeo.Neol saranghameun burwanjeonham witaeroum.Biteulgeorigo jeungo soge michyeodo.Saranghae tto saranghae.Deo jidokhage apeugo shipeo.I unmyeong soge.Geochin nunbit jonjae jeonbu.Girl you're my Favorite.Nunmul ssotgo muneojigo.Yeolgi soge ip majchumyeon.Pokpungcheoreom You're my Favorite.Huhwe eopshi baby.Kkaman bam.When you coming with a storm.Samkyeo beoril deut wabwa.Just watching you.Never satisfy my soul.Neon ajik nareul molla.Jangmineun bulkeunde (See that).Yeorijin anhanne (Hands down).Shimjangeun jogangan geol (Take that).I paguge bam.Neol weonhan daega badadeuryeo.Eotteoke neoreul.Baraji aneul su isseo.My heart when you touch.Jeonyullo momburimchyeo.Saranghae tto saranghae.Deo jidokhage apeugo shipeo.I unmyeong soge.Geochin nunbit jonjae jeonbu.Girl you're my Favorite.Nunmul ssotgo muneojigo.Yeolgi soge ip majchumyeon.Pokpungcheoreom You're my Favorite.Huhwe eopshi baby.Deo tteugeoweojyeodo dwae.Cheongugeul gajyeoon neo.You'll always be my Favorite.Girl you know that you got me.I can't even lie.Naega jeil joahan.You'll always be my Favorite.Saranghae tto saranghae.Deo jidokhage apeugo shipeo.I unmyeong soge.Geochin nunbit jonjae jeonbu.Girl you're my Favorite.Nunmul ssotgo muneojigo.Yeolgi soge ip majchumyeon.Pokpungcheoreom You're my Favorite.You are my Favorite.You are my Favorite.Favorite.Your love your love.You are you are you are.You're my Favorite.Saranghae saranghae my");
        $song1->setCreatedAt(new \DateTimeImmutable());
        $song1->setUpdatedAt(new \DateTimeImmutable());
        $manager->persist($song1);
        $manager->flush();

        $song1 = new Song();
        $song1->setTitle('Korn - Start The Healing');
        $song1->setFullTextInThisColumn("Do you really wanna come with me?.It's hard to see from the eyes of a stranger.Are you ready for the feeling to leave.So that you can breathe and not live with the danger?.But there is always something fighting its way back in.But there is always something pushing me to give in.Do you really wanna make believe.And try to achieve a little break from the anger?.I should've been good.I should've been down.I couldn't let go.What could I do?.I can take it all away, the feelings.Break apart the pain and start the healing.I should've withstood.I shouldn't bow down.I couldn't get through.What could I do?.I can take it all away, the feelings.Break apart the pain and start the healing.Do you really wanna prowl with me?.This travesty cuts sharp like a razor.Are you ready for your scars to bleed?.You will succeed pulling out the invaders.But there is always something fighting its way back in.But there is always something pushing me to give in.Do you really wanna make believe.And try to achieve a little break from the anger?.I should've been good.I should've been down.I couldn't let go.What could I do?.I can take it all away, the feelings.Break apart the pain and start the healing.I should've withstood.I shouldn't bow down.I couldn't get through.What could I do?.I can take it all away, the feelings.Break apart the pain and start the healing.Everything I'm feeling burst into flames.Looking at a soul that's broken and strain.Every night the wish is always the same.Keep on hoping that I don't go insane.The more you fall for it.The more it starts to stick.The more you fall for it.The more it starts to stick.The more you fall for it.The more it starts to stick.The more you fall for it.It's never gonna quit.I should've been good.I should've been down.I couldn't let go.What could I do?.I can take it all away, the feelings.Break apart the pain and start the healing.I should've withstood.I shouldn't bow down.I couldn't get through.What could I do?.I can take it all away, the feelings.Break apart the pain and start the healing.Break apart the pain and start the healing.");
        $song1->setCreatedAt(new \DateTimeImmutable());
        $song1->setUpdatedAt(new \DateTimeImmutable());
        $manager->persist($song1);
        $manager->flush();

        $song1 = new Song();
        $song1->setTitle('Placebo - Surrounded By Spies');
        $song1->setFullTextInThisColumn("I saw you jump from a burning building.I saw you jump from a burning building.I've seen you move like Elvis set on fire.I've seen you move like Elvis set on fire.This search for meaning is killing me.This search for meaning is killing me.This search for meaning is killing me.This search for meaning.Ping pong ball at the back of my throat.Ping pong ball at the back of my throat.And I won't be spoken to like that.And I won't be spoken to like that.Suspicious bag on the platform.Suspicious bag on the platform.Suspicious bag on the platform.Suspicious bag on the platform.Ex-drummer's nose stuck in the past.Ex-drummer's nose stuck in the past.Found dead behind the wheel of a car.Found dead behind the wheel of a car.World leader going under the knife.World leader going under the knife.Stage four.Stage two.Stage three.Stage four.Stage two.Stage three.We go to Sweden in the back of a cab.We go to Sweden in the back of a cab.And every picture house is empty.And every picture house is empty.I gave my heart.Now I want it back.I gave my heart.Now I want it back.I gave my heart.Now I want it back.I gave my heart.Now I want it back.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.Dead fly on the national anthem.Dead fly on the national anthem.Dead fly on the national anthem.Dead fly on the national anthem.I see faces on the bathroom floor.I see faces on the bathroom floor.I see faces on the bathroom floor.Come on over and I'll show you more.Where are you now.When I need you the most.(Shut up).Where are you now.When I need you the most.(Shut up).Where are you now.When I need you the most.(Shut up).Where are you now.When I need you the most.(Shut up).I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.I am surrounded by spies.Spies.Spies.Spies.");
        $song1->setCreatedAt(new \DateTimeImmutable());
        $song1->setUpdatedAt(new \DateTimeImmutable());
        $manager->persist($song1);
        $manager->flush();

        $song1 = new Song();
        $song1->setTitle('Luke Combs - Doin\' This');
        $song1->setFullTextInThisColumn("Someone asked me once in an interview.What was growing up like, where'd you go to school?.And what would you do if you weren't doin' this?.I'd be drivin' my first car, an old worn-out Dodge.Tryin' to make rent with a dead end job, just makin' due.With tips in a jar, my guitar and an old barstool.I'd have a Friday night crowd in the palm of my hand.Cup of brown liquor, couple buddies in a band.Singin' them same damn songs like I am now.I'd be feelin' on fire on a hardwood stage.Bright lights like lightning runnin' through my veins.At the Grand Ole Opry or a show in some no-name town.I'd still be doin' this if I wasn't doin' this.I'd still be the same guy they knew back in the day.Who was burnin' CDs just to give away.Payin' his dues if I wasn't doin' this.Five deep in a van, head full of steam.Hot on the heels of my neon dreams maybe comin' true.Livin' this life just like I was born to do.I'd have a Friday night crowd in the palm of my hand.Cup of brown liquor, couple buddies in a band.Singin' them same damn songs like I am now.I'd be feelin' on fire on a hardwood stage.Bright lights like lightning runnin' through my veins.At the Grand Ole Opry or a show in some no-name town.I'd still be doin' this if I wasn't doin' this.It ain't about the fame.It ain't about the fortune.It ain't about the name.It ain't about the glory.I guess I'm sayin' it's always been about.Having a Friday night crowd in the palm of my hand.Cup of brown liquor, couple buddies in a band.Singin' them same damn songs like I am now.I'd be feelin' on fire on a hardwood stage.Bright lights like lightning runnin' through my veins.At the Grand Ole Opry or a show in some no-name town.I'd still be doin' this if I wasn't doin' this.Someone asked me once in an interview.What was growing up like, where'd you go to school?.And what would you do if you weren't doin' this?");
        $song1->setCreatedAt(new \DateTimeImmutable());
        $song1->setUpdatedAt(new \DateTimeImmutable());
        $manager->persist($song1);
        $manager->flush();
    }
}
